apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/att-user-inquiry
  newTag: 677f935b
- name: asia.gcr.io/poc-innovation-iot/cicd
  newTag: 0e6bfc5a
- name: asia.gcr.io/poc-innovation-iot/example-service
  newTag: 103eda26


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: example-service-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: example-service-secret-env
